server:
  port: 3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/Authentification?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1096170621856-efmec5fj908qt8od0t9m267romucgi0n.apps.googleusercontent.com
            client-secret: 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 
            scope: 
            - email
            - profile
